### ISSUE TITLE
Error when trying to user the store

### ISSUE THREAD

**Issue by custa1200** [manakor/connect-parse#2]
Hi I have copy and pasted the code from your examples on the Github page as follows:

```
var session = require('express-session');
var ParseStore = require('connect-parse')(session);

GLOBAL.Parse = require('parse/node').Parse;
Parse.initialize("id", "key");

app.use(session({
    secret: "secret bit of text that nobody knows",
    store: new ParseStore({
        client: Parse //,
    //parseClassName: "expressSession",
    //ttl: 86400
    }),
    saveUninitialized: true,
    resave: true
}));
```

and I get the following error

```
Cannot call a class as a function

TypeError: Cannot call a class as a function
    at exports.default (/Users/custa/github/Portfolio/portfolioapp/node_modules/parse/node_modules/babel-runtime/helpers/class-call-check.js:5:11)
    at Object.ParseQuery [as Query] (/Users/custa/github/Portfolio/portfolioapp/node_modules/parse/lib/node/ParseQuery.js:117:5)
    at ParseStore.get_ (/Users/custa/github/Portfolio/portfolioapp/node_modules/connect-parse/lib/connect-parse.js:33:29)
    at ParseStore.get (/Users/custa/github/Portfolio/portfolioapp/node_modules/connect-parse/lib/connect-parse.js:53:10)
    at session (/Users/custa/github/Portfolio/portfolioapp/node_modules/express-session/index.js:404:11)
    at Layer.handle [as handle_request] (/Users/custa/github/Portfolio/portfolioapp/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/custa/github/Portfolio/portfolioapp/node_modules/express/lib/router/index.js:312:13)
    at /Users/custa/github/Portfolio/portfolioapp/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/custa/github/Portfolio/portfolioapp/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/custa/github/Portfolio/portfolioapp/node_modules/express/lib/router/index.js:271:10)
```

**Comment by k80w** [comment]
Until @manakor reviews my pull request, you can just replace line 33 of `lib/connect-parse.js` with this:

```
    var query = new this.client.Query(Session);
```
